name : Format Checking

on:
  push:
    branches:
      -main

jobs:
    format:
        runs-on: ubuntu-latest
        name: Run format checking against tf files
        steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: 'Bash script'
          uses: actions/checkout@main
        - run: terraform fmt --recrsive --check --diff